theme: jekyll-theme-cayman

title: Trabajo practico final
description: Pagina del repositorio del trabajo final de taller de programacion FIUBA

show_downloads: true
<a href="andi-carretero.github.io/test_page/documentacion/Documentacion_Tecnica.pdf" target="_blank">PDF.</a>
