theme: jekyll-theme-cayman

title: Trabajo practico final
description: Pagina del repositorio del trabajo final de taller de programacion FIUBA

show_downloads: true
<a href="https://github.com/andi-carretero/test_page/tree/main/documentacion/Documentacion_Tecnica.pdf" class="image fit"><img src="images/marr_pic.jpg" alt=""></a>
